name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push en la rama main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages  # ✅ Agregar esta línea para evitar el error

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist  # Astro genera la carpeta "dist" con los archivos para producción

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
